// Generated by tools/queue_schema.rb; edit protocol/queue.sql and protocol/queue-upgrade.sql.
pub(crate) const FORMAT: i64 = 1;
pub(crate) const CREATE: &str = include_str!("queue.sql");
pub(crate) const UPGRADE: &str = include_str!("queue-upgrade.sql");
