#!/usr/bin/env ruby
# Embeds the device queue schema in every client, so no package reads protocol/ at runtime.

ROOT = File.expand_path('..', __dir__)
NOTICE = "Generated by tools/queue_schema.rb; edit protocol/queue.sql and protocol/queue-upgrade.sql.".freeze

def sql(name)
  File.read(File.join(ROOT, 'protocol', name)).rstrip
end

def format_version
  sql('queue.sql')[/`PRAGMA user_version = (\d+)`/, 1] or abort('protocol/queue.sql names no format')
end

def indented(text)
  text.lines(chomp: true).map { it.empty? ? '' : "    #{it}" }.join("\n")
end

def swift
  <<~SWIFT
    // #{NOTICE}
    enum QueueSchema {
        static let format = #{format_version}

        static let create = """
    #{indented(sql('queue.sql'))}
        """

        static let upgrade = """
    #{indented(sql('queue-upgrade.sql'))}
        """
    }
  SWIFT
end

def kotlin
  <<~KOTLIN
    // #{NOTICE}
    package com.lockvoid.clickman

    internal object QueueSchema {
        const val FORMAT = #{format_version}

        val create: String = """
    #{indented(sql('queue.sql'))}
        """.trimIndent()

        val upgrade: String = """
    #{indented(sql('queue-upgrade.sql'))}
        """.trimIndent()
    }
  KOTLIN
end

def rust
  <<~RUST
    // #{NOTICE}
    pub(crate) const FORMAT: i64 = #{format_version};
    pub(crate) const CREATE: &str = include_str!("queue.sql");
    pub(crate) const UPGRADE: &str = include_str!("queue-upgrade.sql");
  RUST
end

def outputs
  {
    'swift/Sources/ClickMan/QueueSchema.swift' => swift,
    'kotlin/libraries/clickman/src/main/kotlin/com/lockvoid/clickman/QueueSchema.kt' => kotlin,
    'rust/crates/clickman/src/queue_schema.rs' => rust,
    'rust/crates/clickman/src/queue.sql' => "#{sql('queue.sql')}\n",
    'rust/crates/clickman/src/queue-upgrade.sql' => "#{sql('queue-upgrade.sql')}\n"
  }
end

check = ARGV.include?('--check')
stale = outputs.filter_map do |name, text|
  path = File.join(ROOT, name)
  if check
    name unless File.exist?(path) && File.read(path) == text
  else
    File.write(path, text)
    nil
  end
end

abort("Queue schema copies differ from protocol/: #{stale.join(', ')}") unless stale.empty?
